"""Make available balance nullable

Revision ID: 72ac40e55b66
Revises: 0cca41f7deac
Create Date: 2020-10-20 03:15:45.714828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ac40e55b66'
down_revision = '0cca41f7deac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balances', 'available',
               existing_type=sa.NUMERIC(precision=11, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balances', 'available',
               existing_type=sa.NUMERIC(precision=11, scale=2),
               nullable=False)
    # ### end Alembic commands ###
